import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

// POST /api/reports/seed - Seed 30 report catalogs
export async function POST(request: NextRequest) {
  try {
    // Delete existing catalogs
    await prisma.reportCatalog.deleteMany({})

    const catalogs = [
      // 종양/항암 (8)
      {
        title: '한국 비소세포폐암(NSCLC) 치료제 시장 분석 및 전망 2025-2030',
        slug: 'nsclc-market-korea-2025',
        description: '비소세포폐암 치료제 시장의 현황, 면역항암제 중심의 경쟁 환경 분석, EGFR/ALK 표적치료제 시장 전망',
        categories: ['종양/항암'],
        therapeuticArea: '종양학',
        drugName: '면역관문억제제 (PD-1/PD-L1)',
        indication: '비소세포폐암 (NSCLC)',
        marketSizeKrw: BigInt(1800000000000),
        patientPool: 35000,
        availableTiers: ['BASIC', 'PRO', 'PREMIUM'],
      },
      {
        title: '한국 유방암 치료제 시장 보고서 2025-2030',
        slug: 'breast-cancer-market-korea-2025',
        description: 'HER2 양성, 삼중음성 유방암 치료제 시장 분석. ADC, CDK4/6 억제제 등 신규 치료제 파이프라인 전망',
        categories: ['종양/항암'],
        therapeuticArea: '종양학',
        drugName: 'CDK4/6 억제제, ADC',
        indication: '유방암',
        marketSizeKrw: BigInt(1200000000000),
        patientPool: 28000,
        availableTiers: ['BASIC', 'PRO', 'PREMIUM'],
      },
      {
        title: '한국 대장암(CRC) 치료제 시장 분석 2025-2030',
        slug: 'crc-market-korea-2025',
        description: '대장암 항암화학요법 및 표적치료제 시장. KRAS G12C 억제제, 면역항암제 병용요법 전망',
        categories: ['종양/항암'],
        therapeuticArea: '종양학',
        drugName: 'KRAS 억제제, 항EGFR',
        indication: '대장암 (CRC)',
        marketSizeKrw: BigInt(950000000000),
        patientPool: 32000,
        availableTiers: ['BASIC', 'PRO', 'PREMIUM'],
      },
      {
        title: '한국 위암 치료제 시장 보고서 2025-2030',
        slug: 'gastric-cancer-market-korea-2025',
        description: '위암 치료제 시장 현황 및 전망. Claudin 18.2 표적항체, 면역항암 병용요법 분석',
        categories: ['종양/항암'],
        therapeuticArea: '종양학',
        drugName: 'Claudin 18.2 항체, 니볼루맙',
        indication: '위암',
        marketSizeKrw: BigInt(780000000000),
        patientPool: 30000,
        availableTiers: ['BASIC', 'PRO', 'PREMIUM'],
      },
      {
        title: '한국 혈액암(혈액종양) 치료제 시장 분석 2025-2030',
        slug: 'hematologic-cancer-market-korea-2025',
        description: '림프종, 백혈병, 다발성골수종 치료제 시장. CAR-T 세포치료, 이중특이항체 분석',
        categories: ['종양/항암'],
        therapeuticArea: '종양학',
        drugName: 'CAR-T, 이중특이항체',
        indication: '혈액암',
        marketSizeKrw: BigInt(650000000000),
        patientPool: 18000,
        availableTiers: ['BASIC', 'PRO', 'PREMIUM'],
      },
      {
        title: '한국 간암(HCC) 치료제 시장 분석 2025-2030',
        slug: 'hcc-market-korea-2025',
        description: '간세포암 치료제 시장. 면역항암 병용요법, TKI 표적치료제, 한국 B형간염 기반 고위험군 분석',
        categories: ['종양/항암'],
        therapeuticArea: '종양학',
        drugName: '아테졸리주맙+베바시주맙, 렌바티닙',
        indication: '간세포암 (HCC)',
        marketSizeKrw: BigInt(520000000000),
        patientPool: 16000,
        availableTiers: ['BASIC', 'PRO', 'PREMIUM'],
      },
      {
        title: '한국 전립선암 치료제 시장 보고서 2025-2030',
        slug: 'prostate-cancer-market-korea-2025',
        description: '전립선암 호르몬치료, 차세대 항안드로겐제, PARP 억제제 시장 분석 및 전망',
        categories: ['종양/항암'],
        therapeuticArea: '종양학',
        drugName: '엔잘루타마이드, PARP 억제제',
        indication: '전립선암',
        marketSizeKrw: BigInt(420000000000),
        patientPool: 14000,
        availableTiers: ['BASIC', 'PRO'],
      },
      {
        title: '한국 면역항암제(IO) 시장 종합 보고서 2025-2030',
        slug: 'immuno-oncology-market-korea-2025',
        description: 'PD-1/PD-L1, CTLA-4, LAG-3 등 면역관문억제제 전체 시장 분석. 병용요법 트렌드',
        categories: ['종양/항암'],
        therapeuticArea: '종양학',
        drugName: '키트루다, 옵디보, 티센트릭',
        indication: '면역항암 전체',
        marketSizeKrw: BigInt(2200000000000),
        patientPool: 85000,
        availableTiers: ['BASIC', 'PRO', 'PREMIUM'],
      },
      // 대사질환 (5)
      {
        title: '한국 제2형 당뇨병 치료제 시장 분석 2025-2030',
        slug: 'type2-diabetes-market-korea-2025',
        description: 'GLP-1 수용체작용제, SGLT2 억제제 중심 당뇨병 치료제 시장. 비만 동반 치료 시장 확대 전망',
        categories: ['대사질환'],
        therapeuticArea: '대사내분비',
        drugName: 'GLP-1 RA, SGLT2i',
        indication: '제2형 당뇨병',
        marketSizeKrw: BigInt(3500000000000),
        patientPool: 3500000,
        availableTiers: ['BASIC', 'PRO', 'PREMIUM'],
      },
      {
        title: '한국 비만 치료제 시장 보고서 2025-2030',
        slug: 'obesity-market-korea-2025',
        description: '위고비(세마글루타이드), 마운자로(티르제파타이드) 등 GLP-1 기반 비만치료 시장 폭발적 성장 분석',
        categories: ['대사질환'],
        therapeuticArea: '대사내분비',
        drugName: '세마글루타이드, 티르제파타이드',
        indication: '비만',
        marketSizeKrw: BigInt(1500000000000),
        patientPool: 5000000,
        availableTiers: ['BASIC', 'PRO', 'PREMIUM'],
      },
      {
        title: '한국 이상지질혈증 치료제 시장 분석 2025-2030',
        slug: 'dyslipidemia-market-korea-2025',
        description: '스타틴, PCSK9 억제제, 인클리시란 등 이상지질혈증 치료제 시장 및 신규 기전 분석',
        categories: ['대사질환'],
        therapeuticArea: '심혈관/대사',
        drugName: 'PCSK9 억제제, 인클리시란',
        indication: '이상지질혈증',
        marketSizeKrw: BigInt(2800000000000),
        patientPool: 4800000,
        availableTiers: ['BASIC', 'PRO'],
      },
      {
        title: '한국 NASH/MASH 치료제 시장 전망 2025-2030',
        slug: 'nash-market-korea-2025',
        description: '비알코올성 지방간염(NASH/MASH) 최초 승인 치료제 등장. 레스메티롬 시장 분석 및 파이프라인',
        categories: ['대사질환'],
        therapeuticArea: '간질환',
        drugName: '레스메티롬 (Rezdiffra)',
        indication: 'NASH/MASH',
        marketSizeKrw: BigInt(350000000000),
        patientPool: 1200000,
        availableTiers: ['BASIC', 'PRO', 'PREMIUM'],
      },
      {
        title: '한국 통풍 치료제 시장 분석 2025-2030',
        slug: 'gout-market-korea-2025',
        description: '요산 저하제 및 급성 통풍 치료제 시장. 고령화에 따른 환자 증가 및 신규 치료 옵션 분석',
        categories: ['대사질환'],
        therapeuticArea: '류마티스/대사',
        drugName: '페북소스타트, 콜히친',
        indication: '통풍',
        marketSizeKrw: BigInt(280000000000),
        patientPool: 490000,
        availableTiers: ['BASIC', 'PRO'],
      },
      // 자가면역 (4)
      {
        title: '한국 류마티스 관절염(RA) 치료제 시장 분석 2025-2030',
        slug: 'ra-market-korea-2025',
        description: 'TNF 억제제, JAK 억제제, IL-6 억제제 중심 RA 치료제 시장. 바이오시밀러 영향 분석',
        categories: ['자가면역'],
        therapeuticArea: '류마티스',
        drugName: 'JAK 억제제, 바이오시밀러',
        indication: '류마티스 관절염',
        marketSizeKrw: BigInt(980000000000),
        patientPool: 350000,
        availableTiers: ['BASIC', 'PRO', 'PREMIUM'],
      },
      {
        title: '한국 아토피 피부염 치료제 시장 보고서 2025-2030',
        slug: 'atopic-dermatitis-market-korea-2025',
        description: '듀피젠트, JAK 억제제 등 아토피 피부염 생물학적제제 시장. 소아/성인 시장 세분화 분석',
        categories: ['자가면역'],
        therapeuticArea: '피부과',
        drugName: '두필루맙, JAK 억제제',
        indication: '아토피 피부염',
        marketSizeKrw: BigInt(620000000000),
        patientPool: 1500000,
        availableTiers: ['BASIC', 'PRO', 'PREMIUM'],
      },
      {
        title: '한국 건선 치료제 시장 분석 2025-2030',
        slug: 'psoriasis-market-korea-2025',
        description: 'IL-17, IL-23 억제제 중심 건선 생물학적제제 시장 분석 및 경구 소분자 신약 전망',
        categories: ['자가면역'],
        therapeuticArea: '피부과',
        drugName: 'IL-23 억제제, TYK2 억제제',
        indication: '건선',
        marketSizeKrw: BigInt(450000000000),
        patientPool: 320000,
        availableTiers: ['BASIC', 'PRO'],
      },
      {
        title: '한국 염증성 장질환(IBD) 치료제 시장 분석 2025-2030',
        slug: 'ibd-market-korea-2025',
        description: '크론병, 궤양성 대장염 치료제 시장. 항TNF, 항인테그린, JAK 억제제 분석',
        categories: ['자가면역'],
        therapeuticArea: '소화기내과',
        drugName: '우스테키누맙, 베돌리주맙',
        indication: '염증성 장질환 (IBD)',
        marketSizeKrw: BigInt(380000000000),
        patientPool: 85000,
        availableTiers: ['BASIC', 'PRO', 'PREMIUM'],
      },
      // 신경질환 (3)
      {
        title: '한국 알츠하이머 치료제 시장 전망 2025-2030',
        slug: 'alzheimer-market-korea-2025',
        description: '레카네맙, 도나네맙 등 항아밀로이드 항체 치료제 등장. 한국 고령화와 치매 시장 분석',
        categories: ['신경질환'],
        therapeuticArea: '신경과',
        drugName: '레카네맙, 도나네맙',
        indication: '알츠하이머병',
        marketSizeKrw: BigInt(550000000000),
        patientPool: 880000,
        availableTiers: ['BASIC', 'PRO', 'PREMIUM'],
      },
      {
        title: '한국 편두통 치료제 시장 분석 2025-2030',
        slug: 'migraine-market-korea-2025',
        description: 'CGRP 억제제(에레누맙, 프레마네주맙) 중심 편두통 예방치료 시장 분석',
        categories: ['신경질환'],
        therapeuticArea: '신경과',
        drugName: 'CGRP 억제제',
        indication: '편두통',
        marketSizeKrw: BigInt(320000000000),
        patientPool: 620000,
        availableTiers: ['BASIC', 'PRO'],
      },
      {
        title: '한국 다발성경화증(MS) 치료제 시장 분석 2025-2030',
        slug: 'ms-market-korea-2025',
        description: '다발성경화증 DMT 시장. 경구제, 주사제, 고효능 치료제 분석 및 한국 환자 현황',
        categories: ['신경질환'],
        therapeuticArea: '신경과',
        drugName: '오크레부스, 케심프타',
        indication: '다발성경화증',
        marketSizeKrw: BigInt(180000000000),
        patientPool: 5500,
        availableTiers: ['BASIC', 'PRO'],
      },
      // 바이오의약품 (4)
      {
        title: '한국 바이오시밀러 시장 종합 보고서 2025-2030',
        slug: 'biosimilar-market-korea-2025',
        description: '셀트리온, 삼성바이오에피스 중심 한국 바이오시밀러 산업 분석. 글로벌 시장 점유율 전망',
        categories: ['바이오의약품'],
        therapeuticArea: '바이오시밀러',
        drugName: '램시마, 하드리마, 오너스티',
        indication: '바이오시밀러 전체',
        marketSizeKrw: BigInt(4500000000000),
        patientPool: 2500000,
        availableTiers: ['BASIC', 'PRO', 'PREMIUM'],
      },
      {
        title: '한국 ADC(항체-약물 접합체) 시장 분석 2025-2030',
        slug: 'adc-market-korea-2025',
        description: '엔허투, 패드세브 등 ADC 치료제 시장 급성장 분석. 한국 기업 ADC 파이프라인 전망',
        categories: ['바이오의약품'],
        therapeuticArea: '종양학/바이오',
        drugName: 'T-DXd (엔허투), EV',
        indication: 'ADC 치료 전체',
        marketSizeKrw: BigInt(850000000000),
        patientPool: 45000,
        availableTiers: ['BASIC', 'PRO', 'PREMIUM'],
      },
      {
        title: '한국 세포/유전자치료제 시장 전망 2025-2030',
        slug: 'cell-gene-therapy-market-korea-2025',
        description: 'CAR-T, 유전자치료, iPSC 기반 치료제 시장. 인보사, 킴리아 등 한국 시장 진출 분석',
        categories: ['바이오의약품'],
        therapeuticArea: '세포/유전자치료',
        drugName: 'CAR-T (킴리아, 예스카타)',
        indication: '세포/유전자치료 전체',
        marketSizeKrw: BigInt(320000000000),
        patientPool: 12000,
        availableTiers: ['BASIC', 'PRO', 'PREMIUM'],
      },
      {
        title: '한국 mRNA 치료제/백신 시장 분석 2025-2030',
        slug: 'mrna-market-korea-2025',
        description: 'COVID-19 이후 mRNA 플랫폼 확장. 암 백신, 감염병 백신, 희귀질환 치료제 파이프라인',
        categories: ['바이오의약품'],
        therapeuticArea: '백신/면역',
        drugName: 'mRNA 백신, 개인맞춤형 암백신',
        indication: 'mRNA 치료 전체',
        marketSizeKrw: BigInt(680000000000),
        patientPool: 52000000,
        availableTiers: ['BASIC', 'PRO'],
      },
      // 디지털헬스 (3)
      {
        title: '한국 디지털 치료제(DTx) 시장 분석 2025-2030',
        slug: 'dtx-market-korea-2025',
        description: '식약처 허가 디지털 치료제 시장. 불면증, ADHD, 우울증 DTx 분석 및 보험급여 전망',
        categories: ['디지털헬스'],
        therapeuticArea: '디지털헬스',
        drugName: '솜즈, 뉴냅비전',
        indication: '디지털 치료제 전체',
        marketSizeKrw: BigInt(150000000000),
        patientPool: 3200000,
        availableTiers: ['BASIC', 'PRO', 'PREMIUM'],
      },
      {
        title: '한국 AI 신약개발 시장 보고서 2025-2030',
        slug: 'ai-drug-discovery-market-korea-2025',
        description: 'AI 기반 신약 발굴/최적화 시장. 스탠다임, 파로스IBT 등 한국 AI 바이오 기업 분석',
        categories: ['디지털헬스'],
        therapeuticArea: 'AI/빅데이터',
        drugName: 'AI 플랫폼',
        indication: 'AI 신약개발',
        marketSizeKrw: BigInt(250000000000),
        patientPool: 0,
        availableTiers: ['BASIC', 'PRO'],
      },
      {
        title: '한국 원격의료/비대면진료 시장 분석 2025-2030',
        slug: 'telemedicine-market-korea-2025',
        description: '비대면진료 제도화 이후 시장 분석. 원격 모니터링, 디지털 헬스케어 플랫폼 전망',
        categories: ['디지털헬스'],
        therapeuticArea: '디지털헬스',
        drugName: '원격진료 플랫폼',
        indication: '원격의료 전체',
        marketSizeKrw: BigInt(480000000000),
        patientPool: 8500000,
        availableTiers: ['BASIC', 'PRO', 'PREMIUM'],
      },
      // 심혈관 (1)
      {
        title: '한국 심부전 치료제 시장 분석 2025-2030',
        slug: 'heart-failure-market-korea-2025',
        description: 'SGLT2 억제제, ARNI 중심 심부전 치료제 시장. 고령화에 따른 HFpEF/HFrEF 시장 확대',
        categories: ['심혈관'],
        therapeuticArea: '심혈관',
        drugName: '엔트레스토, 포시가, 자디앙',
        indication: '심부전',
        marketSizeKrw: BigInt(720000000000),
        patientPool: 180000,
        availableTiers: ['BASIC', 'PRO', 'PREMIUM'],
      },
      // 건기식 (2)
      {
        title: '한국 프로바이오틱스 시장 분석 2025-2030',
        slug: 'probiotics-market-korea-2025',
        description: '건강기능식품 프로바이오틱스 시장. 장건강, 면역, 피부건강 기능성 세분화 분석',
        categories: ['건기식'],
        therapeuticArea: '건강기능식품',
        drugName: '유산균 복합제',
        indication: '프로바이오틱스',
        marketSizeKrw: BigInt(1100000000000),
        patientPool: 15000000,
        availableTiers: ['BASIC', 'PRO'],
      },
      {
        title: '한국 비타민/미네랄 보충제 시장 보고서 2025-2030',
        slug: 'vitamin-supplement-market-korea-2025',
        description: '비타민D, 오메가3, 멀티비타민 중심 보충제 시장. 고령자/여성/어린이 타겟 세분화',
        categories: ['건기식'],
        therapeuticArea: '건강기능식품',
        drugName: '비타민D, 오메가3',
        indication: '비타민/미네랄 보충제',
        marketSizeKrw: BigInt(890000000000),
        patientPool: 20000000,
        availableTiers: ['BASIC', 'PRO'],
      },
    ]

    let count = 0
    for (const catalog of catalogs) {
      await prisma.reportCatalog.create({
        data: {
          ...catalog,
          priceBasic: 500000,
          pricePro: 1500000,
          pricePremium: 3000000,
        },
      })
      count++
    }

    return NextResponse.json({
      success: true,
      message: `${count}개 보고서 카탈로그가 생성되었습니다`,
      count,
    })
  } catch (error) {
    console.error('[POST /api/reports/seed] Error:', error)
    return NextResponse.json(
      { success: false, error: String(error) },
      { status: 500 }
    )
  }
}
